[package]
name = "vapenation-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1", default-features = false, features = ['std'] }
alloy-rlp = { version = "0.3", features = ["derive"], default-features = false }
alloy-sol-types = { version = "0.7", default-features = false }

vapenation-core = { path = "../../../../common/vapenation-core" }