name: rust common setup 
description: common setup for rust builds
runs:
  using: "composite"
  steps:
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - uses: dtolnay/rust-toolchain@1.79.0
        with:
          components: clippy

      - uses: taiki-e/install-action@cargo-binstall

      - name: Install risc0 tooling
        shell: bash
        run: |
          cargo binstall cargo-risczero -y
          cargo risczero install
          cargo risczero --version

      - name: Install sp1 tooling
        shell: bash
        env:
          SP1_DIR: "/sp1"
        run: |
          curl -L https://sp1.succinct.xyz | bash
          chmod +x /sp1/bin/sp1up
          /sp1/bin/sp1up
          cargo prove --version
