name: rust common setup 
description: common setup for rust builds
runs:
  using: "composite"
  steps:
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - uses: dtolnay/rust-toolchain@1.79.0
        with:
          components: clippy

      - uses: taiki-e/install-action@cargo-binstall

      - name: Install risc0 tooling
        shell: bash
        run: |
          cargo binstall cargo-risczero -y
          cargo risczero install
          cargo risczero --version

      - name: Install sp1 tooling
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          echo "$HOME/.config/.sp1/bin" >> $GITHUB_PATH

      - name: Check sp1 version
        shell: bash
        run: |
          find $HOME -name sp1up
          echo "Checking PATH:"
          echo $PATH
          source /home/runner/.bashrc
          sp1up
          cargo prove --version
