name: rust common setup 
description: common setup for rust builds
runs:
  using: "composite"
  steps:
      - uses: dtolnay/rust-toolchain@1.80.1
        with:
          components: clippy

      - uses: taiki-e/install-action@cargo-binstall

      - name: Install risc0 tooling
        shell: bash
        run: |
          cargo binstall cargo-risczero -y
          cargo risczero install
          cargo risczero --version

      # TODO: https://github.com/InfinityVM/InfinityVM/issues/120
      # - name: Install sp1 tooling
      #   shell: bash
      #   run: |
      #     curl -L https://sp1.succinct.xyz | bash
      #     echo "$HOME/.sp1/bin" >> $GITHUB_PATH
      # - name: Check sp1 version
      #   shell: bash
      #   run: |
      #     sp1up
      #     cargo prove --version

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts
        shell: bash
        run: |
          cd contracts && forge build