name: rust common setup 
description: common setup for rust builds
runs:
  using: "composite"
  steps:
      - name: Install rust nightly toolchain with fmt
        # Make sure to keep this in sync with the version in rust-toolchain.toml
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-01-11
          components: rustc rustfmt cargo clippy

      - name: Install sp1 tooling
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          echo "$HOME/.sp1/bin" >> $GITHUB_PATH
      - name: Check sp1 version
        shell: bash
        run: |
          sp1up --version v3.3.0
          cargo prove --version

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts
        shell: bash
        run: |
          cd contracts && forge build
