[package]
name = "mock-consumer-risc0-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1", default-features = false, features = ['std'] }
alloy = { version = "0", features = ["sol-types"], default-features = false }
