# Dockerfile
   
FROM ghcr.io/foundry-rs/foundry:latest

COPY crates/scripts/src/anvil-devnet-startup.sh /root/scripts/startup.sh
RUN chmod +x /root/scripts/startup.sh
EXPOSE 8545

CMD ["./root/scripts/startup.sh"]
