[package]
name = "vm-comparison"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ivm-zkvm = { workspace = true }
borsh = { workspace = true }
