[package]
name = "clob-test-utils"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
alloy = { workspace = true }
tokio = { workspace = true }
clob-core = { workspace = true }
clob-contracts = { workspace = true }
ivm-test-utils = { workspace = true }
ivm-contracts = { workspace = true }
