// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/eth/eth_client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/eth/eth_client.go -package=mock -destination=pkg/mock/eth_client.go EthClient
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	types "github.com/ethos-works/InfinityVM/server/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockEthClient is a mock of EthClient interface.
type MockEthClient struct {
	ctrl     *gomock.Controller
	recorder *MockEthClientMockRecorder
}

// MockEthClientMockRecorder is the mock recorder for MockEthClient.
type MockEthClientMockRecorder struct {
	mock *MockEthClient
}

// NewMockEthClient creates a new mock instance.
func NewMockEthClient(ctrl *gomock.Controller) *MockEthClient {
	mock := &MockEthClient{ctrl: ctrl}
	mock.recorder = &MockEthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthClient) EXPECT() *MockEthClientMockRecorder {
	return m.recorder
}

// ExecuteCallback mocks base method.
func (m *MockEthClient) ExecuteCallback(job *types.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCallback", job)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteCallback indicates an expected call of ExecuteCallback.
func (mr *MockEthClientMockRecorder) ExecuteCallback(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCallback", reflect.TypeOf((*MockEthClient)(nil).ExecuteCallback), job)
}
