[package]
version = "0.1.0"
name = "vapenation_guest"
edition = "2021"

[dependencies]
serde = { version = "*"}
alloy-rlp = { version = "*", features = ["derive"] }
alloy-sol-types = { version = "*" }
vapenation_core = { path = "../../../risc0/vapenation/core" }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.7-testnet" }

