[package]
name = "clob-contracts"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
alloy = {  workspace = true, features = ["full", "contract", "transport-http", "transport-ws", "network", "providers", "pubsub", "signer-local", "signer-keystore", "rpc-types-debug", "rpc-types-trace", "json-rpc", "rpc-client", "rlp", "sol-types"] }
