[package]
name = "matching-game-sp1-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "8a62caa0b8893aabe8e9477d4568c20387ae4896", features = ["libm", "lib"], default-features = false }
alloy = { version = "0.2", features = ["sol-types"], default-features = false }
bincode = { version = "1.3", default-features = false }
matching-game-core = { path = "../../../core" }
ivm-abi = { path = "../../../../../crates/sdk/abi" }
sha2 = { version = "0.10", default-features = false }
kairos-trie = { git = "https://github.com/cspr-rad/kairos-trie.git", features = ["serde"] }

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", rev = "8a62caa0b8893aabe8e9477d4568c20387ae4896", default-features = false }
sp1-build = { git = "https://github.com/succinctlabs/sp1.git", rev = "8a62caa0b8893aabe8e9477d4568c20387ae4896" } 