// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: server/v1/job.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ZK program verification key
	ProgramVerifyingKey []byte `protobuf:"bytes,1,opt,name=program_verifying_key,json=programVerifyingKey,proto3" json:"program_verifying_key,omitempty"`
	// Program inputs
	Inputs []byte `protobuf:"bytes,2,opt,name=inputs,proto3" json:"inputs,omitempty"`
	// The address of the contract to execute a callback with a result with
	ContractAddress []byte `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// CPU cycle limit for job execution
	MaxCycles uint32 `protobuf:"varint,4,opt,name=max_cycles,json=maxCycles,proto3" json:"max_cycles,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_v1_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_server_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetProgramVerifyingKey() []byte {
	if x != nil {
		return x.ProgramVerifyingKey
	}
	return nil
}

func (x *Job) GetInputs() []byte {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Job) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *Job) GetMaxCycles() uint32 {
	if x != nil {
		return x.MaxCycles
	}
	return 0
}

var File_server_v1_job_proto protoreflect.FileDescriptor

var file_server_v1_job_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x22, 0x9b, 0x01, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x32, 0x0a, 0x15, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x73, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x74, 0x68,
	0x6f, 0x73, 0x2d, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x69, 0x6e, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x79, 0x76, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_v1_job_proto_rawDescOnce sync.Once
	file_server_v1_job_proto_rawDescData = file_server_v1_job_proto_rawDesc
)

func file_server_v1_job_proto_rawDescGZIP() []byte {
	file_server_v1_job_proto_rawDescOnce.Do(func() {
		file_server_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_v1_job_proto_rawDescData)
	})
	return file_server_v1_job_proto_rawDescData
}

var file_server_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_v1_job_proto_goTypes = []any{
	(*Job)(nil), // 0: server.v1.Job
}
var file_server_v1_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_v1_job_proto_init() }
func file_server_v1_job_proto_init() {
	if File_server_v1_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_v1_job_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_v1_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_v1_job_proto_goTypes,
		DependencyIndexes: file_server_v1_job_proto_depIdxs,
		MessageInfos:      file_server_v1_job_proto_msgTypes,
	}.Build()
	File_server_v1_job_proto = out.File
	file_server_v1_job_proto_rawDesc = nil
	file_server_v1_job_proto_goTypes = nil
	file_server_v1_job_proto_depIdxs = nil
}
