[package]
name = "vapenation-core"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-rlp = { version = "0.3", features = ["derive"], default-features = false }
alloy-sol-types = { version = "0.7", default-features = false }
