[package]
name = "test-utils"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "reqwest"] }
prost = { workspace = true }
tokio = { workspace = true }

proto = { path = "../proto" }
zkvm = { path = "../zkvm" }