[package]
name = "cmd"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
alloy = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

