[package]
name = "app"
version = "0.1.0"
edition = "2021"

[workspace]

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = { level = "deny", priority = -1 }
rustdoc.all = "warn"

[[bin]]
name = "matching-game"
path = "src/matching_game.rs"

[dependencies]
alloy = { version = "0", features = ["sol-types"], default-features = false }
risc0-zkvm = { version = "1", default-features = false, features = ['std'] }
borsh = { version = "1", default-features = false }
matching-game-core = { path = "../../core" }
abi = { path = "../../../crates/sdk/abi" }
trie-db = { version = "0.27.0", default-features = false }
keccak-hasher = { version = "0.16.0", default-features = false }
reference-trie = { version = "0.29.1", features = ["std"] }
