[package]
name = "matching-game-sp1"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
once_cell = { workspace = true }
sp1-utils = { path = "../../../../crates/sp1-utils" }

[build-dependencies]
sp1-utils = { path = "../../../../crates/sp1-utils" }
sp1-build = { workspace = true }
sp1-sdk = { workspace = true }
bincode = { workspace = true }