[book]
authors = ["infinityvm Core Contributors"]
language = "en"
multilingual = false
title = "infinityvm Book"

[output.html]
git-repository-url = "https://github.com/infinityvm/infinityvm"
default-theme = "ayu"

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "target/book"
