name: contracts

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/contracts.yml"
      - "**.sol"
  pull_request:
    paths:
      - ".github/workflows/contracts.yml"
      - "**.sol"
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Run Forge tests
        run: |
          forge test -vvv
