name: spelling

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

# Cancel running checks if a new commit is pushed to the same branch (new commit will retrigger checks)
# Docs: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    runs-on: ubicloud-standard-2
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          skip: "*.lock"
          ignore_words_file: .codespellignore
